Real-Dev-Squad/todo-frontend

README.md

Date: 28 Dec 2024
Developer Name: @VaibhavSingh8 
---
N/A
This PR aims to update the README.md for Todo Frontend repository to provide an overview of the project.
</details>
</details>
N/A

Updated README.md for Todo Frontend

---

.gitignore
next.config.ts
package.json
pnpm-lock.yaml

Date: 23-Jan-2025
Developer Name: @VaibhavSingh8 
---
- Added configurations for the build exports in the `out` directory for deploying the Todo frontend repo on Cloudflare pages.
- Pinned node and pnpm versions via `volta`.
- Updated dependencies for latest updates and better management across the project.
<details>
N/A
</details>
<details>
N/A
</details>

Export config for deployment on Cloudflare pages and pinned pnpm and node versions

---

.env.sample
.github/workflows/build-and-test.yml

Date: 10-Feb-2025
Developer Name: @VaibhavSingh8 
---
- closes #14 
This PR aims to automate Tests, Lint and Build checks while raising a PR, ensuring that all the code changes are ready and working for deployment.
Related Design Doc: [Click here](https://docs.google.com/document/d/1TMRIdqa2UprSrIaFtVU8bIIcwGGQP6j3tDqIIGKBe0Q/edit?tab=t.0)
<details>
N/A
</details>
<details>
N/A
</details>

Run Lint, tests and build checks on raising PR

---

.github/workflows/build-and-test.yml
README.md
package.json

Date: `4th June 2025`
Developer Name: `Shubham  Raj`
---
- #45 
- #48
- #44 
- #43
This PR add a new script `pnpm build-with-storybook`, which build the next app along with storybook, used to build storybook in staging environment.
Script changes are done in cloudflare by prakash sir
<details>
<summary>Screencast 1</summary>
https://github.com/user-attachments/assets/8698e14e-93cc-4fe3-a254-bc94852e0fa2
</details>
<details>
<summary>N/A</summary>
N/A
</details>

Dev to main Sync

---

__tests__/unit/Shimmer.test.tsx
app/tasks/page.tsx
components/Shimmer/Shimmer.stories.tsx
test.md

Date: 6 Jul, 2025
Developer Name: @tejaskh3 
- changed the component name
Update component import paths by changing directory names from 'Shimmer' to 'shimmer' to ensure case consistency across the codebase; add a new `test.md` file with code that reads JSON input, creates an element object with attributes, and outputs the result.
The import path changes address inconsistencies in directory casing, which can lead to import errors in environments with case-sensitive file systems. The addition of `test.md` was likely for testing purposes or for providing an example of handling JSON input in Node.js.

fix: component naming

---

app/_provider.tsx
app/layout.tsx
package.json
pnpm-lock.yaml

Date: 6 Jul, 2025
Developer Name: @tejaskh3 
- added tanstack query in the next APP
- added dev tools for tanstack query
Integrate TanStack Query for improved data-fetching capabilities in the application, including adding support for React Query Devtools, and update dependencies to include the necessary TanStack libraries.
These changes aim to establish a robust and efficient data-fetching mechanism using TanStack Query, helping to manage server-state with more ease and flexibility. The addition of React Query Devtools facilitates debugging and monitoring query states during development, enhancing overall productivity and application performance.

feat: add tanstack query

---

components/auth/signin-button.tsx

Date: 
Developer Name: 
---
<details>
</details>
<details>
</details>
Update the Google login URL in the SigninButton component to include a trailing slash.
The trailing slash in the URL is necessary to ensure consistency with backend routing, which might differentiate between URLs with and without a trailing slash; this prevents potential redirect issues and ensures smooth authentication flow.

fix: update Google login URL to include trailing slash

---

app/hooks/useAuth.ts

Date: 
Developer Name: 
---
<details>
</details>
<details>
</details>
Change the `queryKey` value from `["user", "profile"]` to `["users", "profile"]` in the `useAuth` hook.
These changes are being made to ensure consistency with the API's naming convention, which uses the plural form `users`. This helps in aligning the query keys with the server-side expectations and possibly resolves any mismatches or errors that might occur due to the discrepancy in naming.

fix: user api name

---

app/profile/page.tsx
components/NavBar.tsx
components/dashboard/DashboardWelcomeScreen.tsx
components/ui/dropdown-menu.tsx
lib/api/api-client.ts
lib/utils.ts
package.json
pnpm-lock.yaml

Date: 11 July 2025
---
- #88
- Added a new dropdown menu component for user profile actions.
- Implemented user profile page displaying user initials, name, and email.
- Enhanced the navigation bar to include a dropdown for profile and logout options.
- Updated utility functions to generate user initials from the name.
- Integrated logout functionality with API client for user session management.
<details>
https://github.com/user-attachments/assets/63e6905c-3825-4453-bee2-0e742a86a0b5
</details>
<details>
</details>
Integrate dropdown menu and user profile functionality in the navigation bar and user profile page, implement utility functions for user details, and add dependencies for dropdown …

feat: integrate dropdown menu and user profile functionality

---

components/TodoForm.tsx

Date: 12 July 2025
---
- We are showing completed status in the frontend and sending the same in the payload but our backend expect DONE as status
- Fix the issue where we are sending COMPLETE as task status to DONE while we are updating
<details>
https://github.com/user-attachments/assets/d31ad202-60d3-4a1a-b091-ead647776c2d
</details>
<details>
</details>
Update the status option in the `TodoForm` component from "COMPLETED" to "DONE".
The term "DONE" aligns better with the updated status terminology used across the application, ensuring consistency and improving clarity for users selecting task statuses.
> Is this description stale? Ask me to generate a new description by commenting …

refactor: update TodoForm status option from 'COMPLETED' to 'DONE'

---

components/auth/signin-button.tsx

Date: 
Developer Name: 
---
<details>
</details>
<details>
</details>
Remove the trailing slash from the Google login URL in the `SigninButton` component.
Trailing slashes can cause unnecessary redirects or URL mismatches, impacting performance and user experience. Removing the trailing slash ensures consistent behavior and compatibility with URL standards.

fix: remove trailing slash from Google login URL in SigninButton

---

api/tasks/tasks.api.ts
api/tasks/tasks.types.ts
components/TodoForm.tsx
modules/dashboard/components/dashboard-tasks-table.tsx

Date: 15-07-25
Developer Name: @MayankBansal12 
---
- closes #111 
- Implement action to add and remove task in watchlist
<details>
<summary>ScreenCast</summary>
https://github.com/user-attachments/assets/b71a66d5-bea6-4dbc-8d58-f50c81c03761
</details>
Add functionality to enable the addition and removal of tasks in the watchlist within the task management API, along with corresponding UI components.
This change introduces a more flexible and interactive task management system by providing users the capability to manage their tasks through watchlist features, enhancing the utility and user experience of the application. The feature allows for better task tracking and prioritization, with a streamlined process to add or remove tasks from the watchlist.
> Is this description stale? Ask me …

feat: add and remove task in watchlist

---

modules/landing-page/landing-dashboard-overview.tsx

Date: 
Developer Name: 
---
<details>
</details>
<details>
</details>
Replace the dummy user information with the new user "Prakash Sir" and enhance the UI with an AvatarImage component in the dashboard overview.
The dummy user "John" was a placeholder and is now being replaced with "Prakash Sir" to reflect a real user scenario, improving the realism of the interface. Additionally, the inclusion of the AvatarImage component enriches the visual appeal of the dashboard by displaying a user profile picture, offering a more personalized and engaging user experience.

refactor: replace the dummy user with supreme yaskin

---

modules/landing-page/landing-dashboard-overview.tsx

Update the landing page and add support for mobile
**Before**
**After**
Enhance the layout and responsiveness of the `DashboardPreview` component by using responsive flex layouts, updating spacing, animations, transitions, and adapting grid structures for improved mobile experience.
These changes are made to improve the user interface and experience on different screen sizes, ensuring a more adaptable and visually appealing layout. The updates address the need for a more responsive design, improving the accessibility and usability of the dashboard on mobile devices while also enhancing the visual feedback with animations and transitions.

Enhance DashboardPreview layout and responsiveness

---

api/tasks/tasks.types.ts
components/edit-task-button.tsx
components/todo-labels-list.tsx
components/todo-labels-table.tsx
components/todo-list-table.tsx
lib/utils.ts
modules/dashboard/components/dashboard-watchlist-tasks-table.tsx

Date: 18 July 2025
---
- Introduced a new Label type for better label handling in tasks.
- Updated TTask and TEditTask types to support labels as an array of Label objects.
- Modified EditTaskButton to accommodate the new label structure and ensure compatibility with existing data.
- Added TodoLabelsTable component for displaying task labels in a visually appealing manner.
- Enhanced TodoListTable to integrate TodoLabelsTable for improved task representation.
- Implemented hexToRgba utility function for color manipulation in labels.
<details>
</details>
<details>
</details>
Integrate label management and editing functionality into the task management system by enabling task objects to include …

feat: enhance task management with labels and edit functionality

---

api/tasks/tasks.enum.ts
components/create-edit-todo-form.tsx
components/edit-task-button.tsx
components/todo-status-table.tsx
modules/dashboard/components/create-todo-button.tsx

Date: 18 July 2025
---
- Renamed TASK_STATUS_ENUM value from 'COMPLETED' to 'DONE' for consistency.
- Added status field to CreateEditTodoForm, allowing users to select task status.
- Updated EditTaskButton to handle status updates when editing tasks.
- Enhanced TodoStatusTable to reflect the new status naming convention.
- Integrated status handling in CreateTodoButton for task creation.
<details>
</details>
<details>
</details>
> [!NOTE]
> I'm currently writing a description for your pull request. I should be done shortly (<1 minute). Please don't edit the description field until I'm finished, or we may overwrite each other. If I find nothing to write about, I'll delete this message.

feat: update task status handling and integrate into forms and component

---

api/tasks/tasks.types.ts
modules/dashboard/components/dashboard-tasks-table.tsx
modules/dashboard/components/dashboard-watchlist-tasks-table.tsx

Date: 18 July 2025
---
- fix the issue where labels are not showing in the watchlist task tab
<details>
</details>
<details>
</details>
Refactor task label handling by changing the `labels` type from `string[]` to `TLabel[]` and utilizing the `TodoLabelsList` component for consistent label display in the dashboard Watchlist components.
The change improves the type safety and clarity of the code by using a more appropriate type (`TLabel`), and enhances the maintainability and readability of the label display code through the `TodoLabelsList` component, which consolidates label handling logic. This refactor also sets a foundation for future enhancements in task label management.
> Is this …

fix: labels not rendering in the watchlist task tab

---

api/tasks/tasks.api.ts

Date: 19 July 2025
---
- Update the task update endpoint
<details>
</details>
<details>
</details>
Update the API endpoint for task updates to include the '/update' path in the URL.
The existing endpoint URL was incorrect, lacking the '/update' suffix, which is required by the server to correctly route update requests. Adjusting the URL ensures compatibility and proper handling of task update operations.

fix: update API endpoint for task updates to include '/update' in

---

components/app-sidebar.tsx
config/app-config.ts

Date: 19 July 2025
---
Closes #140
Add link to `/` route to Header in Sidebar for better UX and update app name
<details>
</details>
<details>
</details>
Add a link to the dashboard route in the sidebar header by wrapping the app name within a `<Link>` component.
This change improves the user experience by allowing users to quickly navigate to the dashboard from any part of the application through the sidebar header. This approach ensures the app name in the sidebar header is both informative and functional.

Update app name and update header to route to home root

---

api/tasks/tasks.api.ts
api/tasks/tasks.types.ts
api/teams/teams.api.ts
components/reassign-user.tsx
components/team-user-search-dropdown.tsx
components/todo-list-table.tsx
components/user-search-dropdown.tsx
modules/dashboard/components/create-todo-button.tsx
modules/teams/components/teams-layout-header.tsx
modules/teams/team-tasks.tsx

Date: 19 July 2025
Developer Name: yash raj
---
- N/A
- Adds the ability to reassign a task for a spoc from the teams page.
- Hide actions from the dashboard if the task is assigned to a team. 
Add functionality to re-assign tasks to different users including new API endpoints, UI components for user selection, and integration into task management interfaces.
The changes enable team leads to easily re-assign tasks to other team members, improving task management flexibility. This feature is essential for optimizing workloads and adapting to team dynamics. The implementation involves adding a new `reassignTask` API method and UI components that facilitate user selection and task reassignment, ensuring a seamless user experience.
> Is this description stale? Ask me to generate a new …

feat: add ability to re-assign tasks

---

components/app-sidebar.tsx
modules/teams/components/teams-layout-header.tsx

Date: 19-07-2025
Developer Name: Rishi Chaubey
---
- Integrated a dropdown in sidebar, clicking on which the team list appears
- Added  a seperator
- added cursor pointer
<details>
</details>
<details>
</details>
Integrate a collapsible dropdown feature in the teams section of the sidebar, enhancing the sidebar component by rearranging "Create a team" and "Join a team" links and managing their visibility using expandable/collapsible options.
The primary objective is to improve sidebar navigation by providing a cleaner, more organized view through collapsible sections, improving usability, and making sidebar links more accessible and user-friendly, particularly for managing team-related links. The approach also ensures that …

Chore: Integrate dropdown in teams sidebar

---

components/Animated-logo.tsx
components/page-container-with-logo.tsx
modules/teams/create-team.tsx
modules/teams/join-team.tsx

Date: 19 July 2025
Developer Name: yash raj
---
- N/A
- update create team and join team UI.
Update the UI for "Create" and "Join a Team" routes by incorporating a new `PageContainerWithLogo` component, which embeds a logo into the page layout for enhanced visual consistency and improved aesthetics.
The changes are made to provide a cohesive visual design across the app, particularly for the onboarding flow when creating or joining a team, using a consistent logo placement and design. Integrating the `PageContainerWithLogo` simplifies maintenance and enhances user experience by keeping the visual elements uniform throughout these critical user interactions.

feat: update ui for create and join a team routes

---

api/tasks/tasks.api.ts
api/tasks/tasks.types.ts
components/edit-task-button.tsx
components/reassign-user.tsx
components/ui/checkbox.tsx
modules/dashboard/components/create-todo-button.tsx
modules/dashboard/components/dashboard-tabs.tsx
modules/dashboard/index.tsx
modules/teams/team-tasks.tsx
package.json
pnpm-lock.yaml

Date: 24 Jul 2025
---
Add checkbox to include Done tasks
<details>
</details>
<details>
</details>
Implement a new feature that adds a checkbox to toggle the display of completed tasks in the dashboard.
This change allows users to optionally include completed tasks in their task list, enhancing user control and customization of task visibility. The implementation leverages the `Radix UI` checkbox component for consistent UI styling and behavior, and involves modifications in the types, API calls, and dashboard components.

Checkbox for done task

---

components/todo-list-table.tsx
components/ui/switch.tsx
modules/dashboard/components/dashboard-tabs.tsx
package.json
pnpm-lock.yaml

Date: 24 Jul 2025
---
Closes #157 
This PR updates the UI to use a switch instead of checkbox for including done tasks
<details>
</details>
<details>
</details>
Update the TodoListTable component to use a switch component for toggling the inclusion of done tasks, replacing the prior use of checkboxes, and integrate the new switch functionality throughout the user interface.
This change enhances user experience by implementing a more intuitive switch component for displaying completed tasks, addressing a UI/UX design improvement. The update includes necessary package additions for `@radix-ui/react-switch` and adapts the TodoListTable to seamlessly integrate with existing routing and state-handling …

Update the UI to use a switch component for including done tasks

---

api/teams/teams.api.ts
api/teams/teams.type.ts
components/teams/TeamActivity.tsx
components/teams/TeamActivityCard.tsx
lib/team-utils.ts

Date: 28 Jul 2025
---
Closes [todo-backend#123](https://github.com/Real-Dev-Squad/todo-backend/issues/222)
This PR integrates team audit API in the frontend which is responsible for showing logs of actions taken in a team.
- Integrated API in TeamActivity component which was using hardcoded values earlier.
- Added component for different states like isLoading, isError.
- Added utility function to generate title, description, icon and date for each type of action
<details>
</details>
<details>
</details>
Integrate the team activities API into the application to display a timeline of activities associated with a team.
These changes are being made to replace dummy data with real team activity logs …

Integrate team audit api

---

README.md

Date: 02-08-25
Developer Name: Shobhan Sundar Goutam (@shobhan-sundar-goutam)
---
This pull request refines the README documentation in the following ways:
- Updates the local `/etc/hosts` entry in the "Setup SSL proxy" section
- Revised from `127.0.0.1 staging-todo.realdevsquad.com` to `127.0.0.1 dev.realdevsquad.com` as required for staging API access in local development.
- Streamlines the proxy setup instructions to better guide new contributors on the correct process for enabling SSL API calls to staging.
These changes ensure developers can quickly configure their local environment without confusion, helping teams onboard and test features more efficiently.
<details>
</details>
<details>
</details>
Correct the local host …

Update README: Fix /etc/hosts and SSL proxy setup instructions

---

api/tasks/tasks.types.ts
lib/todo-util.ts
modules/dashboard/components/create-todo-button.tsx

Date: 04 Aug 2025
---
Closes [todo-backend#239](https://github.com/Real-Dev-Squad/todo-backend/issues/239)
This PR updates the data sent to create task and update task api to send user's timezone data which will be used to validate dueDate on backend. Types have also been updated accordingly.
<details>
https://github.com/user-attachments/assets/b30d6f36-07ec-45c3-88b2-dc8cffbaa4b0
</details>
<details>
</details>
> [!NOTE]
> I'm currently writing a description for your pull request. I should be done shortly (<1 minute). Please don't edit the description field until I'm finished, or we may overwrite each other. If I find nothing to write about, I'll delete this message.

fix(due-at): update to send timezone for validation

---

components/todo-list-table.tsx

Date: 8 Aug 2025
---
- Include done task toggle not visible on default page
- create a variable to store the logic to show the done task toggle button and based on that render the toggle 
<details>
</details>
<details>
</details>
> [!NOTE]
> I'm currently writing a description for your pull request. I should be done shortly (<1 minute). Please don't edit the description field until I'm finished, or we may overwrite each other. If I find nothing to write about, I'll delete this message.

fix(todo-list-table): update include done tasks toggle logic 

---

components/todo-list-table.tsx

Date: 09-08-2025
Developer Name: Shobhan Sundar Goutam (@shobhan-sundar-goutam)
---
- Fixed a bug in the Watchlist where a user could edit any task, even if it was not assigned to them.  
- Now, the edit option is only available for tasks assigned to the logged-in user.
<details>
- Before change:
- After change:
</details>
<details>
</details>
Restrict the edit access of tasks in the Watchlist to only users who are assigned to those tasks.
Previously, any user could edit tasks regardless of their assignment status, which could lead to unauthorized modifications. By using the authentication hook to check if the current user matches the task assignee, we ensure that only authorized users can make edits, enhancing the security …

Restrict task edit access in Watchlist to assigned users only

---

app/(internal-routes)/admin/page.tsx

Date: 21 Aug 2025
---
-  Fix the build issue
<details>
</details>
<details>
</details>
Refactor the admin page by separating content rendering into the `AdminContent` component and wrapping it with React's `Suspense` for improved loading handling.
These changes enhance the structure of the admin page by improving its performance and user experience. The introduction of `Suspense` provides a more graceful loading user interface, and the utilization of `useCallback` ensures stable function references, optimizing the React rendering process.

refactor(admin-page): enhance admin page structure with Suspense 

---

src/api/teams/teams.api.ts
src/api/teams/teams.enum.ts
src/api/teams/teams.type.ts
src/components/teams/leave-team-button.tsx
src/components/teams/team-members.tsx
src/lib/team-utils.ts
src/modules/teams/components/leave-team-dialog.tsx
src/modules/teams/components/teams-layout-header.tsx

Date: 21 Sept 2025
---
PR going in prod:
#193 
<details>
</details>
<details>
</details>
Add remove member functionality for teams, including API endpoints (removeFromTeam, getUserRoles), new typings and enums (TeamRoles, RolesScope), enhanced activity types (MEMBER_REMOVED_FROM_TEAM, MEMBER_LEFT_TEAM), UI dialogs for removing members and leaving teams, and conditional UI to show leave option based on user role.
Introduce proper role-based member management and auditing, enabling admins to remove members and users to leave teams, while surfacing relevant team roles and activity history in the UI. This approach centralizes permission handling and improves UX with confirm dialogs and contextual …

feat(#170): add remove member functionality (#193)
